version: "3.8"

services:

  db_master:
    container_name: 'db_master'
    build:
      context: ./project/db_master
      dockerfile: Dockerfile
    restart: always
    hostname: ${MYSQL_HOST_NAME_MASTER}
    networks:
      dapp_ns:
        # ipv4_address: 172.16.238.2
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_SPIDER_PASSWORD: ${MYSQL_SPIDER_PASSWORD}
      MYSQL_HOST_NAME_MASTER: ${MYSQL_HOST_NAME_MASTER}
      MYSQL_HOST_NAME_SPIDER: ${MYSQL_HOST_NAME_SPIDER}
    volumes:
      - type: bind
        source: ./project/db_master/initdb
        target: /docker-entrypoint-initdb.d
      - type: bind
        source: ./project/db_master/conf/my.cnf
        target: /etc/mysql/conf.d/my.cnf
      - type: bind
        source: ./logs/db_master
        target: /var/log/mysql
      #- type: bind
      #  source: ./project/db_spider/data
      #  target: /var/lib/mysql

  db_spider:
    container_name: 'db_spider'
    build:
      context: ./project/db_spider
      dockerfile: Dockerfile
    restart: always
    hostname: ${MYSQL_HOST_NAME_SPIDER}
    networks:
      dapp_ns:
        # ipv4_address: 172.16.238.3
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_SPIDER_PASSWORD: ${MYSQL_SPIDER_PASSWORD}
      MYSQL_HOST_NAME_MASTER: ${MYSQL_HOST_NAME_MASTER}
      MYSQL_HOST_NAME_SPIDER: ${MYSQL_HOST_NAME_SPIDER}
    volumes:
      - type: bind
        source: ./project/db_spider/initdb
        target: /docker-entrypoint-initdb.d
      - type: bind
        source: ./project/db_spider/conf/my.cnf
        target: /etc/mysql/conf.d/my.cnf
      - type: bind
        source: ./logs/db_spider
        target: /var/log/mysql
      - type: bind
        source: ./logs/initdb
        target: /var/log/initdb
      #- type: bind
      #  source: ./project/db_spider/data
      #  target: /var/lib/mysql
    depends_on:
      - db_master

  web:
    container_name: 'web'
    build:
      context: ./project/web
      dockerfile: Dockerfile
    restart: always
    hostname: web-server
    networks:
      dapp_ns:
        # ipv4_address: ${WEB_HOST_ADDR}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_HOST_NAME_SPIDER: ${MYSQL_HOST_NAME_SPIDER}
      WEB_HOST_ADDR: ${WEB_HOST_ADDR}
    ports:
      - 80:80
    volumes:
      - type: bind
        source: ./project/web/public
        target: /var/www/public
      - type: bind
        source: ./project/web/app
        target: /var/www/app
      - type: bind
        source: ./logs/web
        target: /var/log/apache2
      - type: bind
        source: ./project/volumes/web/app/twitteroauth
        target: /var/www/app/twitteroauth
      - type: bind
        source: ./project/volumes/web/app/site.php
        target: /var/www/app/site.php
      - type: bind
        source: ./project/volumes/web/public/rss
        target: /var/www/public/rss
      - type: bind
        source: ./project/volumes/web/public/sitemap.xml
        target: /var/www/public/sitemap.xml
    depends_on:
      - db_spider

  cron:
    container_name: 'cron'
    build:
      context: ./project/cron
      dockerfile: Dockerfile
    init: true
    networks:
      dapp_ns:
        # ipv4_address: 172.16.238.6
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_HOST_NAME_SPIDER: ${MYSQL_HOST_NAME_SPIDER}
      TZ: ${TZ}
    volumes:
      - type: bind
        source: ./project/cron/cron.d/cron.txt
        target: /etc/crontab
      - type: bind
        source: ./project/cron/script
        target: /cron_script
      - type: bind
        source: ./logs/cron
        target: /var/log/cron
      - type: bind
        source: ./project/volumes/web/public/rss
        target: /output/rss
      - type: bind
        source: ./project/volumes/web/public/sitemap.xml
        target: /output/sitemap.xml
    depends_on:
      - web

  phpmyadmin:
    container_name: 'phpmyadmin'
    image: 'phpmyadmin:5.1.0'
    restart: always
    networks:
      dapp_ns:
        # ipv4_address: 172.16.238.5
    ports:
      - 8081:80
    environment:
      - PMA_HOSTS=${MYSQL_HOST_NAME_MASTER},${MYSQL_HOST_NAME_SPIDER}
      - PMA_ARBITRARY=-1
    depends_on:
      - cron

networks:
  dapp_ns:
    driver: bridge
    # ipam:
    #   driver: default
    #   config:
    #     - subnet: 172.16.238.0/24
    #       gateway: 172.16.238.1
